updating everything

diff --git a/jobs/ops_manager/templates/ctl.erb b/jobs/ops_manager/templates/ctl.erb
--- a/jobs/ops_manager/templates/ctl.erb
+++ b/jobs/ops_manager/templates/ctl.erb
@@ -1,28 +1,136 @@
 #!/bin/bash
 
- RUN_DIR=/var/vcap/sys/run/ops_manager
- LOG_DIR=/var/vcap/sys/log/ops_manager
- PIDFILE=${RUN_DIR}/pid
- OPS_DIR=/var/vcap/store/ops_manager
+RUN_DIR=/var/vcap/sys/run/ops_manager
+LOG_DIR=/var/vcap/sys/log/ops_manager
+PIDFILE=${RUN_DIR}/pid
+OPS_DIR=/var/vcap/store/ops_manager
+APP_DIR=/var/vcap/packages/mongodb-mms-3.6.1
+APP_NAME="mms-app"
+APP_ENV="hosted"
+APP_ID="mms"
+BASE_PORT="8080"
+BASE_SSL_PORT="8443"
+JAVA_HOME="${APP_DIR}/jdk"
+MMS_USER=vcap
+ENC_KEY_PATH=${APP_DIR}/gen.key
+ENC_KEY=<%= properties.ops_manager.enc_key_b64 %>
+URI_STR=<%= properties.ops_manager.uri %>
 
- case $1 in
+######################## build_opts
+build_opts() {
+    local opts="$1"
+    local arr="${!2}"
+    for opt in "${arr[@]}"; do
+        opts="${opts} ${opt}"
+    done
+    echo -n $opts
+}
 
+case $1 in
    start)
      mkdir -p $RUN_DIR $LOG_DIR $OPS_DIR
      chown -R vcap:vcap $RUN_DIR $LOG_DIR $OPS_DIR
      echo $$ > $PIDFILE
-     ###  "Jobs never depend on other jobs." @http://bosh.io/docs/create-release.html
+     base64 -d ${ENC_KEY} >  ${ENC_KEY_PATH}
+     chmod 600 ${ENC_KEY_PATH}
+
+     ### "Jobs never depend on other jobs." 
+ 	 ### ^  @http://bosh.io/docs/create-release.html
      ### /gif angry
-     ### Conclusion: Relying on PreFlight Checks by mongodb-mms and monit retry attempts
-     exec /var/vcap/packages/ops_manager/bin/mongodb-mms start
+     ### Conclusion: Relying on PreFlight Checks by mongodb-mms and monit retry
+	 ### attempts
+     
+	 sed -i.bak 's/^\(LOG_PATH=\).*/\1/var/vcap/sys/log/ops_manager'${APP_DIR}/conf/mms.conf
+     sed -i.bak 's/^\(MMS_USER=\).*/\1vcap'                         ${APP_DIR}/conf/mms.conf
+     sed -i.bak 's/^\(JAVA_HOME=\).*/\1/var/vcap/packages/mongodb-mms-3.6.1/lib/jdk'   ${APP_DIR}/conf/mms.conf
+     sed -i.bak "s/^\(ENC_KEY_PATH=\).*/\1${ENC_KEY_PATH}"          ${APP_DIR}/conf/mms.conf
+     sed -i.bak "s/^\(mongo.mongoUri=\).*/\1${URI_STR}              ${APP_DIR}/conf/conf-mms.properties
+     
+	 ### Stripped from .../init.d/mongodb-mms.service
+     # 
+     # pushd mongodb-mms
+	 ### source the init-functions, other functions have been copied above the case statement.
+ 	######################### preFlightCheck
+ 	${JAVA_HOME}/bin/${APP_NAME} \
+          -Dcore.preflight.class=com.xgen.svc.mms.MmsPreFlightCheck \
+      -Dlog_path=${LOG_DIR}/ops_manager.stdout \
+      -Duser.timezone=GMT     -Dfile.encoding=UTF-8 \
+      -Dserver-env=${APP_ENV} -Dapp-id=${APP_ID} -Dmms.keyfile=${ENC_KEY_PATH} \
+      -Xmx256m -XX:-OmitStackTraceInFastThrow \
+      -classpath ${APP_DIR}/classes/mms.jar:${APP_DIR}/conf:${APP_DIR}/lib/* \
+      com.xgen.svc.core.PreFlightCheck \
+      >>  ${LOG_DIR}/ops_manager.stdout.log \
+      2>> ${LOG_DIR}/ops_manager.stderr.log
+ 	if [[ $? != 0 ]]; then
+    	exit 1
+ 	fi
+	######################### migrate
+	${JAVA_HOME}/bin/${APP_NAME} \
+      -Dmms.migrate=all \
+          -Dcore.preflight.class=com.xgen.svc.mms.MmsPreFlightCheck \
+      -Dlog_path=${LOG_DIR}/ops_manager.stdout \
+      -Duser.timezone=GMT     -Dfile.encoding=UTF-8 \
+      -Dserver-env=${APP_ENV} -Dapp-id=${APP_ID} -Dmms.keyfile=${ENC_KEY_PATH} \
+      -Xmx256m -XX:-OmitStackTraceInFastThrow \
+      -classpath ${APP_DIR}/classes/mms.jar:${APP_DIR}/conf:${APP_DIR}/lib/* \
+      com.xgen.svc.common.migration.MigrationRunner \
+      >>  ${LOG_DIR}/ops_manager.stdout.log \
+      2>> ${LOG_DIR}/ops_manager.stderr.log
+ 	if [[ $? != 0 ]]; then
+     exit 1
+	fi
+ 	ulimit -n 64000 > /dev/null 2>&1
+ 	ulimit -u 64000 > /dev/null 2>&1
+ 	if ulimit -a | grep -q "\-v)" >/dev/null 2>&1; then
+    	ulimit -v unlimited > /dev/null 2>&1
+	fi
+	############################## START
+	opts_array=(
+         "-Dlog_path=${LOG_DIR}/ops_manager.stdout"
+         "-Duser.timezone=GMT"
+         "-Dfile.encoding=UTF-8"
+         "-Dsun.net.client.defaultReadTimeout=20000"
+         "-Dsun.net.client.defaultConnectTimeout=10000"
+         "-Dorg.eclipse.jetty.util.UrlEncoding.charset=UTF-8"
+         "-Dorg.eclipse.jetty.server.Request.maxFormContentSize=4194304"
+         "-Dserver-env=${APP_ENV}"
+         "-Dapp-id=${APP_ID}"
+         "-Dbase-port=${BASE_PORT}"
+         "-Dbase-ssl-port=${BASE_SSL_PORT}"
+         "-Dapp-dir=${APP_DIR}"
+         "-Dxgen.webServerReuseAddress=true"
+         "-Dmms.keyfile=${ENC_KEY_PATH}"
+         "-XX:SurvivorRatio=12"
+         "-XX:MaxTenuringThreshold=15"
+         "-XX:CMSInitiatingOccupancyFraction=62"
+         "-XX:+UseCMSInitiatingOccupancyOnly"
+         "-XX:+UseConcMarkSweepGC"
+         "-XX:+UseParNewGC"
+         "-XX:+UseBiasedLocking"
+         "-XX:+CMSParallelRemarkEnabled"
+         "-XX:-OmitStackTraceInFastThrow"
+         "-classpath ${APP_DIR}/classes/mms.jar:${APP_DIR}/agent:${APP_DIR}/agent/backup:${APP_DIR}/agent/monitoring:${APP_DIR}/agent/automation:${APP_DIR}/data/unit:${APP_DIR}/conf/:${APP_DIR}/lib/*"
+ )
+ 	jvm_opts=$( build_opts "${JAVA_MMS_UI_OPTS}" opts_array[@] )
+ 	jvm_opts_instance="${jvm_opts} -Dinstance-id=0 -Dpid-filename=${PIDFILE}"
+ 	exec ${JAVA_HOME}/bin/${APP_NAME} ${jvm_opts_instance} com.xgen.svc.core.ServerMain & \
+      >>  ${LOG_DIR}/ops_manager.stdout.log \
+      2>> ${LOG_DIR}/ops_manager.stderr.log
+
+     # popd
+     ### This causes monit to PID the mongodb-mms script as opposed to the
+     ### process itself, hence the above refractoring
+     # exec /var/vcap/packages/mongodb-mms-3.6.1/bin/mongodb-mms start 
      ;;
 
    stop)
-     /var/vcap/packages/ops_manager/bin/mongodb-mms stop
-     rm -f $PIDFILE
+	 kill ${PIDFILE} 1>/dev/null 2>&1
+	 sleep 22
+     kill -9 ${PIDFILE} 1>/dev/null 2>&1 
+     rm -f ${PIDFILE}
      ;;
 
    *)
      echo "Usage: ctl {start|stop}" ;;
 
- esac
+esac
